package com.poplicus.crawler.codegen;

public final class Constants {

	//General
	public static final String SPACE = " ";
	public static final String HYPEN = "-";
	public static final String OPEN_PARENTHESIS = "(";
	public static final String CLOSE_PARENTHESIS = ")";
	public static final String OPEN_BRACES = "{";
	public static final String CLOSE_BRACES = "}";
	public static final String TAB = "\t";
	public static final String TAB_TAB = "\t\t";
	public static final String NEW_LINE = "\n";
	public static final String STATIC = "static";
	public static final String FINAL = "const" ;
	public static final String EQUALS = "=";
	public static final String EQUALS_CONDITION = "==";
	public static final String SEMI_COLON = ";";
	public static final String COMMA = ",";
	public static final String COLON = ":";
	public static final String DOT = ".";
	public static final String LOGICAL_COMPLEMENT = "!";
	public static final String BASE = "base";
	public static final String THREE_TABS = "\t\t\t";
	public static final String FOUR_TABS = "\t\t\t\t";
	public static final String FIVE_TABS = "\t\t\t\t\t";
	public static final String OVERRIDE = "override";
	public static final String NEW_LINE_TAB_TAB = "\n\t\t";
	public static final String TAB_TAB_OPEN_BRACE = "\t\t{";
	public static final String TAB_TAB_CLOSE_BRACE = "\t\t}";
	public static final String CONTAINS = "Contains";
	public static final String DOUBLE_QUOTE = "\"";
	public static final String CLICK_ELEMENT = "ClickElement";
	public static final String SELECT_OPTION_ITEM_WITH_ON_CHANGE = "SelectOptionItemWithOnChange";
	public static final String AUTOMATION_TASK_PERFORM_ENTER_DATA = "AutomationTask_PerformEnterData";
	public static final String SET_NEXT_FILE_DOWNLOAD_PATH_AND_NAME = "SetNextFileDownloadPathAndName";
	public static final String LOCATION_URL = "LocationUrl";
	public static final String NOT_EQUALS_CONDITION = "!=";
	public static final String LESS_THAN = "<";
	public static final String LESS_THAN_AND_EQUALS = "<=";
	public static final String LOGICAL_AND = "&&";
	public static final String LOGICAL_OR = "||";
	public static final String FORWARD_SLASH = "/";
	public static final String UNDER_SCORE = "_";
	public static final String NAVIGATE = "Navigate";
	public static final String COLLECT_RESULT_LINKS = "CollectResultLinks";
	public static final String PARSE_RESULTS = "ParseResults";
	public static final String FROM = "From";
	public static final String USING_SPACE = "using ";
	public static final String HTML = "html";
	public static final String STRING = "string";
	public static final String TEXT = "Text";
	public static final String SET_VALUE = "SetValue";
	public static final String APPLY = "Apply";
	public static final String CLEAR = "Clear";
	public static final String USER_INPUT = "userInput";
	public static final String NEXT_ACTION = "NextAction";
	public static final String ACCESSED = "accessed";
	public static final String TRUE = "true";
	public static final String LINE_OF_CODE_IMPLEMENTATION_WARNING = "//** Need to implement the logic to extract this data. **//";
    public static final String RETURN = "return";
    public static final String START = "Start";
    public static final String HREF = "href";
    public static final String HTTP_COLON_2_SLASHES = "http://";
    public static final String HTTPS_COLON_2_SLASHES = "https://";
    public static final String WWW = "www";
    public static final String MAILTO_COLON = "mailto:";
    public static final String DOT_DOT = "..";

	//Table Names
	public static final String BID_TABLE = "Bid";
	public static final String POP_BID_TABLE = "PopBid";
	public static final String POP_BID_INDUSTRY_CODE_TABLE = "PopBidIndustryCode";
	public static final String POP_BID_LOCATION_TABLE = "PopBidLocation";
	public static final String POP_BID_CONTACT_TABLE = "PopBidContact";
	public static final String POP_BID_SET_ASIDE_TABLE = "PopBidSetAside";
	public static final String POP_BID_DOCUMENT_TABLE = "PopBidDocument";
	
	//Crawler Types
	public static final String BID_CRAWLER = "Bid";
	public static final String ORG_CRAWLER = "Organization";
	public static final String BID_RESULTS_CRAWLER = "BidResults";
	public static final String PLAN_HOLDERS_CRAWLER = "PlanHolders";
	
	//Column Names
	public static final String BID_NUMBER = "BidNumber";
	public static final String POSTED_DATE = "PostedDate";
	public static final String PROPOSAL_TYPE = "ProposalType";
	public static final String AMENDMENT_VERSION = "AmendmentVersion";
	public static final String SOURCE_PROPOSAL_TYPE = "SourceProposalType";
	public static final String SUBMITTAL_DATE = "SubmittalDate";
	public static final String VENDOR_NAME = "Name";
	public static final String AWARD_AMOUNT = "AwardAmount";
	public static final String ADVERTISED_DATE ="AdvertisedDate";
    public static final String TITLE = "Title";
    public static final String URL = "URL";
    public static final String AGENCY_NAME = "AgencyName";
    public static final String AWARD_NUMBER = "AwardNumber";
    public static final String AWARD_DATE = "AwardDate";
    public static final String DESCRIPTION = "Description";
    public static final String SOURCE_NAME = "SourceName";
    public static final String SOURCE_ID = "SourceID";
    public static final String SCAN_ID = "ScanID";
    public static final String SITE_NAME = "SiteName";
    public static final String NO_COLUMN_MAPPING = "NO_COLUMN_MAPPING";
    public static final String INDUSTRY_CODE_ID = "IndustryCode_ID";
    public static final String CITY = "City";
    public static final String STATE = "State";
    public static final String UNPARSED_CONTENT = "UnparsedContent";
    public static final String EMAIL = "Email";
    public static final String PHONE = "Phone";
    public static final String FAX = "Fax";
    public static final String FIRST_NAME = "FirstName";
    public static final String LAST_NAME = "LastName";
    public static final String MIDDLE_NAME = "MiddleName";
    public static final String DBE_CODE = "Dbe_code";
    public static final String RESULTSET = "ResultSet";

    //Operators
    public static final String PLUS = "+";
    public static final String MINUS = "-";
    public static final String MULTIPLY = "*";
    public static final String DIVIDE = "/";
    public static final String MODULUS = "%";

    //Web Page Table Column Numbers
    public static final int WEBPAGE_SUMMARY_TABLE_NAME = 0;
    public static final int WEBPAGE_SUMMARY_TABLE_TYPE = 1;
    public static final int WEBPAGE_SUMMARY_TABLE_BROWSER_TO_EXECUTE = 2;
    public static final int WEBPAGE_SUMMARY_TABLE_NAVIGATION_ORDER = 3;
    public static final int WEBPAGE_SUMMARY_TABLE_EXECUTE_ONCE = 4;

    //XML tag names & attributes
    public static final String CRAWLER_TAG = "crawler";
    public static final String CONSTRUCTOR_TAG = "constructor";
    public static final String PARAMETERS_TAG = "parameters";
    public static final String PARAMETER_TAG = "parameter";
    public static final String VALUE_TAG = "value";
    public static final String SOURCE_MAP_CONFIG_TAG = "source-map-config";
    public static final String SUPER_CONSTRUCTOR_TAG = "super-constructor";
    public static final String PRIMARY_BROWSER_TAG = "primary-browser";
    public static final String SECONDARY_BROWSER_TAG = "secondary-browser";
    public static final String TERTIARY_BROWSER_TAG = "tertiary-browser";
    public static final String CONDITIONS_TAG = "conditions";
    public static final String CONDITION_TAG = "condition";
    public static final String LHS_OPERAND_TAG = "lhsOperand";
    public static final String OPERATOR_TAG = "operator";
    public static final String TYPE_TAG = "type";
    public static final String BROWSER_TAG = "browser";
    public static final String RHS_OPERAND_TAG = "rhsOperand";
    public static final String WEB_PAGES_TAG = "web-flows";
    public static final String WEB_PAGE_TAG = "web-flow";
    public static final String URL_TAG = "url";
    public static final String MAIN_IF_TAG = "main_if";
    public static final String IF_TAG = "if";
    public static final String ELSE_IF_TAG = "else-if";
    public static final String ELSE_TAG = "else";
    public static final String LINE_OF_CODE_TAG = "line-of-code";
    public static final String LHS_DEFINITION_TAG = "lhs-definition";
    public static final String RHS_DEFINITION_TAG = "rhs-definition";
    public static final String VARIABLE_TAG = "variable";
    public static final String FUNCTION_DEFINITION_TAG = "function_definition";
    public static final String SUPPORTING_FUNCTION_TAG = "supporting_function";
    public static final String ACTION_TAG = "action";
    public static final String ELEMENT_TAG = "element";
    public static final String NAVIGATE_TAG = "navigate";
    public static final String EXPRESSION_TAG = "expression";
    public static final String OPERAND_TAG = "operand";
    public static final String STRING_TAG = "string";
    public static final String RESULTSET_GROUP_TAG = "resultset-group";
    public static final String RESULTSET_TAG = "resultset";
    public static final String DATUM_TAG = "datum";
    public static final String START_TAG = "start-tag";
    public static final String END_TAG = "end-tag";
    public static final String CONFIG_SUPPORTING_FUNCTIONS_TAG = "supporting-functions";
    public static final String CONFIG_SUPPORTING_FUNCTION_TAG = "supporting-function";
    public static final String SUPPORTED_FIELDS_TAG = "supported-fields";
    public static final String FIELD_TAG = "field";
    public static final String COLUMN_DEFINITION_TAG = "column-definition";
    public static final String DEFAULT_COLUMN_VALUE_MAPPING_TAG = "default-column-value-mapping"; 
    public static final String DEFAULT_VALUE_TAG = "default-value";
    
    public static final String C_ATTR_NAME = "name";
    public static final String C_ATTR_TYPE = "type";
    public static final String C_ATTR_HANDLE_POPUP = "handlePopup";
    public static final String C_ATTR_CLIENT_NAME = "clientName";
    public static final String C_ATTR_SITE_NAME = "siteName";
    public static final String C_ATTR_SOURCE_ID = "sourceID";
    public static final String C_ATTR_SOURCE_NAME = "sourceName";
    public static final String C_ATTR_INVOKE_BASE_PBC = "invokeBasePBC";
    public static final String C_ATTR_INVOKE_BASE_SBC = "invokeBaseSBC";
    public static final String C_ATTR_INVOKE_BASE_TBC = "invokeBaseTBC";
    public static final String C_ATTR_INVOKE_SOURCE_MAP_CONFIG = "invokeSourceMapConfig";
    public static final String C_ATTR_PASS_BY_VALUE = "passByValue";
    public static final String C_ATTR_PASS_BY_REFERENCE = "passByReference";
    public static final String C_ATTR_SECURED_WEB_PAGE = "securedWebpage";
    public static final String C_ATTR_DOWNLOAD_IMAGES = "downloadImages";
    public static final String C_ATTR_DOWNLOAD_SCRIPTS = "downloadScripts";
    public static final String C_ATTR_SUPER_CONDITION = "superCondition";
    public static final String C_ATTR_NAVIGATION_ORDER = "navigationOrder";
    public static final String C_ATTR_EXECUTE_ONCE = "executeOnce";
    public static final String C_ATTR_BROWSER = "browser";
    public static final String C_ATTR_BROWSER_TYPE = "browserType";
    public static final String C_ATTR_PACKAGE_NAME = "packageName";
    public static final String C_ATTR_CLASS_NAME = "className";
    public static final String C_ATTR_ELEMENT_TAG_TYPE = "elementTagType";
    public static final String C_ATTR_ELEMENT_FIELD_TYPE = "elementFieldType";
    public static final String C_ATTR_EXACT_MATCH = "exactMatch";
    public static final String C_ATTR_TABLE_NAME = "tableName";
    public static final String C_ATTR_UNIQUE_ID = "uniqueID";
    public static final String C_ATTR_COLUMN_NAME = "columnName";
    public static final String C_ATTR_DATA_TYPE = "dataType";
    public static final String C_ATTR_VARIABLE_NAME = "variableName";
    public static final String C_ATTR_HTML_SOURCE = "htmlSource";
    public static final String C_ATTR_START_TAG = "startTag";
    public static final String C_ATTR_END_TAG = "endTag";
    public static final String C_ATTR_ENTIRE_STRING = "entireString";
    public static final String C_ATTR_AFTER_TAG = "afterTag";
    public static final String C_ATTR_WHAT_OBJECT = "whatObject";
    public static final String C_ATTR_IS_CONFIGURABLE = "configurable";
    public static final String C_ATTR_STATIC_ACCESS = "staticAccess";
    public static final String C_ATTR_INSTANCE_ACCESS = "instanceAccess";
    public static final String C_ATTR_VARIABLE_REFERENCE_NAME = "variableReferenceName";
    public static final String C_ATTR_VALUE = "value";
    public static final String C_ATTR_TAG_TYPE = "tagType";
    public static final String C_ATTR_USED_IN_BID_CRAWLER = "usedInBidCrawler";
    public static final String C_ATTR_USED_IN_ORG_CRAWLER = "usedInOrgCrawler";
    public static final String C_ATTR_USED_IN_BID_RESULTS_CRAWLER = "usedInBidResultsCrawler";
    public static final String C_ATTR_USED_IN_PLAN_HOLDERS_CRAWLER = "usedInPlanHolderCrawler";
    public static final String C_ATTR_DISPLAY_NAME = "displayName";
    public static final String C_ATTR_DEFAULT_VALUE = "defaultValue";
    public static final String C_ATTR_SHOW_IN_UI = "showInUI";

    //RHS Types with space
    public static final String RHS_TYPE_WITH_SPACE_ASSIGN_VALUE_TO_AN_EXISTING_VARIABLE = "Assign Value To An Existing Variable";
    public static final String RHS_TYPE_WITH_SPACE_RETURN_VALUE_FROM_ACTION = "Return Value From Action";
    public static final String RHS_TYPE_ASSIGN_VALUE_TO_AN_EXISTING_VARIABLE = "AssignValueToAnExistingVariable";
    public static final String RHS_TYPE_RETURN_VALUE_FROM_ACTION = "ReturnValueFromAction";
    public static final String RHS_TYPE_EXPRESSION = "Expression";
    public static final String RHS_TYPE_NO_RHS = "No RHS";

    //Web Page Type
    public static final String WEB_PAGE_TYPE_SEARCH = "Search";
    public static final String WEB_PAGE_TYPE_RESULTLINKS = "ResultLinks";
    public static final String WEB_PAGE_TYPE_RESULT = "Result";
}
